# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - alan-test-20240719(alan-test-b)

on:
  push:
    branches:
      - b
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_84525c2bee8b4d20837d989b941d9e1c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fd6cd00aee204eeeb26fa127ce298d5b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_84525c2bee8b4d20837d989b941d9e1c }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'alan-test-b'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'alan-test-20240719'
        slot-name: 'alan-test-b'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0c2db58a9db4446485f885aac535ac27 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_84525c2bee8b4d20837d989b941d9e1c }}/appsvc/staticsite:${{ github.sha }}'